version: 2

conda:
  environment: docs/conda-env.yml

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - method: setuptools
      path: .

# Build documentation in the doc/source directory with Sphinx
sphinx:
  configuration: docs/conf.py
