version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

conda:
  environment: docs/conda-env.yml

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.9
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

# Build documentation in the doc/source directory with Sphinx
sphinx:
  configuration: docs/conf.py
