dist: bionic
language: python
python:
- 3.7
- 3.8
#- 3.9-dev
install: pip install -e .[test] tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: FAUYpQkV2Jckk3IONjwAh0cZJFpJyQ0V19zjSx51ulvi7PQ5LrdRZW3Kb85m14/9GTRl0oZ2ukAEch25Fs0054ZlXWqV785sALksfPPzPctNYxgMEB29NutQ1uhBIDIJVy28Cq8UmbxqQ6TimYB5aU4eHOpwS8QrQC0Y4/y7+8oPXqvyJSZmep3qf+X9TRBS2TOCP6hoaJinDrA7TNusbXIeR1KHvuf/J3ntmCX+iqiobLzxjJY1cghstTUoRn0dz/XtDUO8MkP5/UeuevlKFNcDFbH3U6/x5ImzKhxGeWUrD+wZirSoEh9ckTrsCUgLgbA5p9JJ73j+ycTNLpS2CSQCCZy4g0FcapZR9QXEj1SIDPHEWbv5fUXvIz4w3lZFZ+J71EPURpUtnyTH0VKOkwv6JKxTPbyg77u9Fp1UCEo6L7K1VUhv2ZuNVmholrlkBu8B0op52x7MD9YSNQeDfIq1PjF/MPN/CVSsr+W3b1HzZs1Xx2h3H/l5uN1E7MPBfuufzQZkWsrY1+3/u6VSmoaQ5mBuYI2LzrbxHknqev3m3K1tcNCaU0U30uYblUTZHaoWxYCtkVjvKCMXADXRUDgje7zj2s3Gxmc5wsbQ+BKJaO9elIzygwqXpy5WysU/FgM5uP9aeuzWL0PU4UQ34lj+PkI7dWF4TOU1KmdvLZ0=
  on:
    tags: true
    repo: jboynyc/textnets
    python: 3.8
