name: rtd-sphinx-build
channels:
  - conda-forge
dependencies:
  - python=3.8.2
  - python-igraph>=0.8.2
  - leidenalg>=0.8.0
  - pandas>=1.0.3
  - spacy>=2.2.4
  - spacy-model-en_core_web_sm
  - toolz
  - click
  - jupyter_sphinx
  - sphinx
  - sphinx_rtd_theme
