# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: textnets CI

on:
  push:
    branches: [ $default-branch, "dev" ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          brew install cairo
        fi
        python -m pip install poetry
        poetry install --no-dev
        poetry install -E test
    - name: Lint with flake8
      run: |
        poetry run flake8 textnets tests
    - name: Test with pytest
      run: |
        poetry run pytest
